@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Nov 22 20:16:00 +0200 2022
REM SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
REM
REM IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim CPU_tb_behav -key {Behavioral:sim_1:Functional:CPU_tb} -tclbatch CPU_tb.tcl -view C:/Users/ikrame.rekabi/Desktop/arch_project_M3_submission/Project_mileStone2_I_M/Project_mileStone1/lab5_Maram_Ikrame.srcs/sim_1/imports/Project_mileStone1/CPU_tb_behav.wcfg -log simulate.log"
call xsim  CPU_tb_behav -key {Behavioral:sim_1:Functional:CPU_tb} -tclbatch CPU_tb.tcl -view C:/Users/ikrame.rekabi/Desktop/arch_project_M3_submission/Project_mileStone2_I_M/Project_mileStone1/lab5_Maram_Ikrame.srcs/sim_1/imports/Project_mileStone1/CPU_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
